version: '3'

services:
  temporal:
    image: temporalio/auto-setup:1.12.2
    environment:
      - CASSANDRA_SEEDS=cassandra
      - TEMPORAL_LISTENER_ADDRESS=0.0.0.0
    ports:
      - "7233:7233"
    depends_on:
      - cassandra
    links:
      - cassandra

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

  temporal-web:
    image: temporalio/web:latest
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
    ports:
      - "8088:8088"
    depends_on:
      - temporal

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./node_modules/@ninetydays/orm-setup/docker/db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    container_name: redis

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
