version: '3'

services:
  temporal:
    image: temporalio/auto-setup:1.12.2
    environment:
      - CASSANDRA_SEEDS=cassandra
      - TEMPORAL_LISTENER_ADDRESS=0.0.0.0
    ports:
      - "7233:7233"
    depends_on:
      - cassandra
    links:
      - cassandra

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

  temporal-web:
    image: temporalio/web:latest
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
    ports:
      - "8088:8088"
    depends_on:
      - temporal
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./node_modules/@ninetydays/orm-setup/docker/db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    container_name: redis
